name: knowledge
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - aws-cdk-lib
    - boto3
    - langchain
    - openai
    - slack_sdk
    - requests
    - pinecone-client
    - pymongo
    - bs4
    - fake_useragent
    - atlassian-python-api